import { test, expect } from '@playwright/test';

test('EdicionGrupo', async ({ page }) => {
  await page.goto('https://mesabosques.bits.bo/auth/login');
  await page.getByRole('textbox', { name: 'Nombre Usuario / Correo' }).click();
  await page.getByRole('textbox', { name: 'Nombre Usuario / Correo' }).fill('admin');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('sample');
  await page.getByRole('button', { name: 'Acceder' }).click();
  await page.locator('a').filter({ hasText: 'Miembros y Comite' }).click();
  await page.getByRole('link', { name: ' Grupos de Trabajo' }).click();
  await page.getByRole('button', { name: '' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Nombre:' }).click();
  await page.getByRole('textbox', { name: 'Nombre:' }).fill('Grupo Prueba 2 editado');
 // await page.getByLabel('Cliente1').getByRole('button', { name: 'Remove' }).click();
  await page.getByRole('combobox', { name: 'Seleccionar Fecha' }).click();
  await page.locator('span').filter({ hasText: '18' }).click();
  await page.getByText('19').click();
  await page.getByRole('combobox', { name: 'Sesiones de la MBC' }).click();
  await page.getByText('Grupo de trabajo', { exact: true }).click();
  await page.getByRole('button', { name: ' Guardar' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.getByRole('textbox', { name: 'Nombre:' }).click();
  await page.getByRole('textbox', { name: 'Nombre:' }).fill('Grupo Prueba 3 editado');
  await page.getByRole('combobox', { name: 'Seleccionar Fecha' }).click();
  await page.locator('span').filter({ hasText: '18' }).click();
  await page.getByText('19').click();
 // await page.locator('#pn_id_56 chevrondownicon path').click();
  await page.locator('.p-multiselect-dropdown').click();
  await page.getByRole('checkbox', { name: 'jose' }).check();
  await page.getByRole('checkbox', { name: 'juan', exact: true }).check();
  await page.getByRole('button', { name: ' Guardar' }).click();
  await page.locator('a').filter({ hasText: 'Log Out' }).click();
});