import { test, expect } from '@playwright/test';

test('NuevaActividadDOS', async ({ page }) => {
  await page.goto('https://mesabosques.bits.bo/auth/login');
  await page.getByRole('textbox', { name: 'Nombre Usuario / Correo' }).click();
  await page.getByRole('textbox', { name: 'Nombre Usuario / Correo' }).fill('admin');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('sample');
  await page.getByRole('button', { name: 'Acceder' }).click();
  await page.locator('a').filter({ hasText: 'Reuniones y Convocatorias' }).click();
  await page.getByRole('link', { name: ' Administración de Agenda' }).click();
  await page.locator('.p-ripple.p-button.p-component.p-button-icon-only').first().click();
  await page.getByRole('button', { name: ' Crear Actividad' }).click();
  await page.getByRole('textbox', { name: 'Actividad:' }).click();
  await page.getByRole('textbox', { name: 'Actividad:' }).fill('PruebaDos');
  await page.getByRole('combobox', { name: 'Seleccione tipo de Actividad' }).click();
  await page.getByRole('option', { name: 'Extraordinaria' }).click();
  await page.getByRole('button', { name: ' Agregar Tarea' }).click();
  await page.getByRole('textbox', { name: 'Tarea' }).click();
  await page.getByRole('textbox', { name: 'Tarea' }).fill('Prueba');
  await page.getByRole('combobox', { name: 'Seleccionar Fecha' }).click();
  await page.getByRole('gridcell', { name: '8', exact: true }).click();
  await page.getByRole('textbox', { name: 'Resultado Esperado' }).click();
  await page.getByRole('textbox', { name: 'Resultado Esperado' }).fill('Exito');
  await page.getByRole('combobox', { name: 'Seleccione respondable' }).click();
  await page.getByRole('option', { name: 'Pruebatres' }).click();
  await page.getByRole('button', { name: ' Agregar Tarea' }).click();
  await page.getByRole('button', { name: '' }).nth(1).click();
  await page.getByRole('button', { name: ' Guardar' }).click();
  await page.locator('a').filter({ hasText: 'Log Out' }).click();
});