import { test, expect } from '@playwright/test';

test('Nuevo_usuario', async ({ page }) => {
  await page.goto('https://mesabosques.bits.bo/auth/login');
  await page.getByRole('textbox', { name: 'Nombre Usuario / Correo' }).click();
  await page.getByRole('textbox', { name: 'Nombre Usuario / Correo' }).fill('admin');
  await page.getByRole('textbox', { name: 'Nombre Usuario / Correo' }).press('Tab');
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('sample');
  await page.getByRole('button', { name: 'Acceder' }).click();
  await page.locator('a').filter({ hasText: 'Administración de Usuarios' }).click();
  await page.getByRole('link', { name: ' Configuración de Usuarios' }).click();
  await page.getByRole('button', { name: ' Agregar Usuario' }).click();
  await page.getByRole('button', { name: ' Agregar Usuario' }).click();
  await page.getByRole('textbox', { name: 'Nombres' }).fill('Pruebas_uno');
  await page.getByRole('textbox', { name: 'Apellido Paterno' }).click();
  await page.getByRole('textbox', { name: 'Apellido Paterno' }).fill('Pruebas _uno');
  await page.getByRole('textbox', { name: 'Apellido Materno' }).click();
  await page.getByRole('textbox', { name: 'Apellido Materno' }).fill('pruebas_uno');
  await page.getByRole('textbox', { name: 'Dirección' }).click();
  await page.getByRole('textbox', { name: 'Dirección' }).fill('Calle_pruebas');
  await page.getByRole('textbox', { name: 'CI', exact: true }).click();
  await page.getByRole('textbox', { name: 'CI', exact: true }).fill('784651');
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).fill('jahilo3187@hosintoy.com');
  await page.getByText('* Ya existe un registro con').click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).click();
  await page.getByRole('textbox', { name: 'Correo Electrónico' }).fill('xivaj19700@hosintoy.com');
  await page.getByRole('textbox', { name: 'Teléfono' }).click();
  await page.getByRole('textbox', { name: 'Teléfono' }).fill('4614612');
  await page.getByRole('dialog', { name: 'Agregar Usuario' }).getByLabel('dropdown trigger').click();
  await page.getByLabel('Documentador').getByText('Documentador').click();
  await page.getByRole('textbox', { name: 'Nombre de Usuario' }).click();
  await page.getByRole('textbox', { name: 'Nombre de Usuario' }).fill('Pruebas_uno');
  await page.getByRole('combobox', { name: 'Usuario válido hasta' }).click();
  await page.getByText('31', { exact: true }).click();
  await page.getByRole('button', { name: ' Guardar' }).click();
  await page.getByText('Guardado con éxito').click();
  await page.locator('div').filter({ hasText: 'Correcto Guardado con éxito' }).nth(2).click();
  await page.getByRole('tab', { name: ' Usuarios por Revisar' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.locator('div').filter({ hasText: 'Correcto Usuario aprobado' }).nth(2).click();
  await page.getByRole('tab', { name: ' Usuarios Aprobados' }).click();
  await page.getByRole('button', { name: '' }).first().click();
  await page.locator('div').filter({ hasText: 'Informacion Enviando correo...' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Correcto Correo enviado' }).nth(2).click();
  await page.locator('a').filter({ hasText: 'Log Out' }).click();
  await page.goto('https://mesabosques.bits.bo/auth/confirmation/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InhpdmFqMTk3MDBAaG9zaW50b3kuY29tIiwiaWQiOjE2LCJ1c2VyIjoiUHJ1ZWJhc191bm8iLCJpYXQiOjE3NTI3NjEwMzYsImV4cCI6MTc1Mjg0NzQzNn0.4E2GEIiGhu7Q2lGMTwJzVoVmeITuaPD0RpXFyQkL7yk');
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).fill('sample');
  await page.getByText('* El campo debe tener más de').click();
  await page.getByText('* Debe contener al menos un s').click();
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).click();
  await page.getByRole('textbox', { name: 'Contraseña', exact: true }).fill('123456789Lp$');
  await page.getByRole('textbox', { name: 'Repetir Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Repetir Contraseña' }).fill('123456789Lp$');
  await page.getByRole('button', { name: 'Confirmar' }).click();
  await page.locator('div').filter({ hasText: 'Correcto Cuenta confirmada' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Correcto Cuenta confirmada' }).nth(2).click(); 
});