import { test, expect } from '@playwright/test';

test('NuevaReunion3', async ({ page }) => {
  await page.goto('https://mesabosques.bits.bo/auth/login');
  await page.getByRole('textbox', { name: 'Nombre Usuario / Correo' }).click();
  await page.getByRole('textbox', { name: 'Nombre Usuario / Correo' }).fill('admin');
  await page.getByRole('textbox', { name: 'Contraseña' }).click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('sample');
  await page.getByRole('button', { name: 'Acceder' }).click();
  await page.locator('a').filter({ hasText: 'Miembros y Comite' }).click();
  await page.getByRole('link', { name: ' Grupos de Trabajo' }).click();
  await page.getByRole('button', { name: '' }).nth(1).click();
  await page.getByRole('button', { name: ' Crear Reunion' }).click();
  await page.getByRole('textbox', { name: 'Nombre:' }).click();
  await page.getByRole('textbox', { name: 'Nombre:' }).fill('Reunionnueva2');
  await page.locator('#fechaReunion').click();
  await page.getByRole('gridcell', { name: '22' }).click();
  await page.locator('#fechaSegundaReunion').click();
  await page.getByRole('gridcell', { name: '27' }).click();
  await page.getByRole('combobox', { name: 'Seleccione Modalidad' }).click();
  await page.getByRole('option', { name: 'Virtual' }).click();
  await page.getByRole('button', { name: ' Guardar' }).click();
  await page.getByRole('button', { name: ' Crear Reunion' }).click();
  await page.getByRole('textbox', { name: 'Nombre:' }).click();
  await page.getByRole('textbox', { name: 'Nombre:' }).fill('reunionpreprueba2');
  await page.locator('#fechaReunion').click();
  await page.getByRole('gridcell', { name: '25' }).click();
  await page.locator('#fechaSegundaReunion').click();
  await page.getByRole('gridcell', { name: '27' }).click();
  await page.getByRole('combobox', { name: 'Seleccione Modalidad' }).click();
  await page.getByRole('option', { name: 'Presencial' }).click();
  await page.getByRole('button', { name: ' Guardar' }).click();
  await page.locator('a').filter({ hasText: 'Log Out' }).click();
});